server:
  #启动端口
  port: 9216
  #开启优雅停机，默认是【IMMEDIATE】，立即停机
  shutdown: GRACEFUL
spring:
  profiles:
    active: dev #本地开发环境
  #    active: prod #线上环境
  application:
    #系统服务名
    name: SpringBootTemplate
  #配置数据库链接信息
  datasource:
    url: jdbc:mysql://${MYSQL_URL}/smartchat?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ${MYSQL_PASSWORD}
#    driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  data:
    #Redis相关参数配置
    redis:
      host: ${REDIS_URL}
      port: 6379
      timeout: 5000
      password:
      jedis:
        pool:
          enabled: true
          maxActive: 30 #给定时间可以分配的最大连接数。 使用负值表示没有限制
          maxIdle: 30  #最大空闲连接数
          minIdle: 10 # 最小空间连接数
          maxWait: -1 #连接池最大等待时间 -1没有限制
#  mail:
#    host: smtp.office365.com
#    port: 587
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            enable: true
#            protocols: TLSv1.2
#          socketFactory:
#            fallback: false
#            port: 587
#            class: javax.net.ssl.SSLSocketFactory
  mail:
    host: smtp.qq.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          ssl:
            enable: true
            protocols: TLSv1.2
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    port: 465


#MyBatis-Plus相关配置
mybatis-plus:
  #指定Mapper.xml路径，如果与Mapper路径相同的话，可省略
  mapper-locations: classpath:cn/wujiangbo/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰大小写自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台sql输出

system:
  name: SpringBootTemplate
  version: 2.3.4

