spring:
  netty:
    leak-detection: paranoid

############################### Turms ###############################

turms:
  cluster:
    connection:
      server:
        port-auto-increment: true
    shared-config:
      mongo:
        uri: ${MONGODB_URL2}
  gateway:
    admin-api:
      debug:
        enabled: true
    client-api:
      logging:
        heartbeat-sample-rate: 1
        included-notification-categories:
          - category: all
      return-reason-for-server-error: true
    fake:
      enabled: true
    mongo:
      admin:
        uri: ${MONGODB_URL2}
      user:
        uri: ${MONGODB_URL2}
  logging:
    console:
      enabled: true
  plugin:
    js:
      debug:
        enabled: true
